# Generated by Django 6.0.5 on 2026-05-19 21:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPackage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(help_text='Connector slug, e.g. "fathom", "gmail".', max_length=64, verbose_name='provider')),
                ('provider_item_id', models.CharField(help_text="Upstream provider's stable id for this item.", max_length=255, verbose_name='provider item id')),
                ('provider_item_type', models.CharField(help_text='E.g. "meeting", "email", "issue".', max_length=64, verbose_name='provider item type')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='title')),
                ('occurred_at', models.DateTimeField(blank=True, help_text='When the source event happened.', null=True, verbose_name='occurred at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('storage_key', models.CharField(help_text='Key under STORAGES["default"], e.g. "{ws}/fathom/meetings/{id}.json".', max_length=500, verbose_name='storage key')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_packages', related_query_name='delivery_package', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Delivery Package',
                'verbose_name_plural': 'Delivery Packages',
                'db_table': 'delivery_packages',
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['workspace', 'provider', 'occurred_at'], name='delivery_pa_workspa_9cc45e_idx'), models.Index(fields=['workspace', 'occurred_at'], name='delivery_pa_workspa_9e6ebc_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'provider', 'provider_item_id'), name='uq_delivery_package_workspace_provider_item')],
            },
        ),
    ]
