# Generated by Django 6.0.5 on 2026-05-21 21:34

import django.db.models.deletion
import donna.core.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCredentials',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(help_text='Stable identifier; matches connector class ``oauth_provider_slug`` (e.g. "google", "fathom").', max_length=64, verbose_name='slug')),
                ('display_name', models.CharField(max_length=120, verbose_name='display name')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='is enabled')),
                ('client_id', models.CharField(blank=True, default='', max_length=255, verbose_name='client id')),
                ('client_secret', donna.core.db.fields.EncryptedTextField(blank=True, null=True, verbose_name='client secret')),
                ('redirect_uri', models.URLField(blank=True, default='', verbose_name='redirect uri')),
                ('authorize_url', models.URLField(blank=True, default='', verbose_name='authorize url')),
                ('token_url', models.URLField(blank=True, default='', verbose_name='token url')),
                ('default_scopes', models.JSONField(blank=True, default=list, verbose_name='default scopes')),
                ('webhook_secret', donna.core.db.fields.EncryptedTextField(blank=True, null=True, verbose_name='webhook secret')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, help_text='Leave empty to make this the deployment-wide default for the slug. Set to a workspace to override the default for that workspace only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_credentials', related_query_name='client_credentials', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Client Credentials',
                'verbose_name_plural': 'Client Credentials',
                'db_table': 'client_credentials',
            },
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', donna.core.db.fields.EncryptedTextField(blank=True, null=True, verbose_name='access token')),
                ('refresh_token', donna.core.db.fields.EncryptedTextField(blank=True, null=True, verbose_name='refresh token')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the current access_token expires (UTC).', null=True, verbose_name='access token expiry')),
                ('scope', models.TextField(blank=True, null=True, verbose_name='scope')),
                ('granter', models.ForeignKey(blank=True, help_text='User who authorized a workspace-scoped token.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_oauth_tokens', related_query_name='granted_oauth_token', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', related_query_name='token', to='integrations.clientcredentials')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_tokens', related_query_name='oauth_token', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_tokens', related_query_name='oauth_token', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'OAuth token',
                'verbose_name_plural': 'OAuth tokens',
                'db_table': 'oauth_tokens',
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_slug', models.CharField(help_text='Connector slug, e.g. "gmail", "drive", "fathom".', max_length=50, verbose_name='provider slug')),
                ('config', models.JSONField(blank=True, default=dict, help_text='User-editable. Validated by Provider.config_schema (JSON Schema) on every PATCH.', verbose_name='config')),
                ('state', models.JSONField(blank=True, default=dict, help_text='Sync-task-managed. Shape: {streams: {<id>: {...}}, global: {...}}.', verbose_name='state')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='last synced at')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='last error at')),
                ('last_error_msg', models.TextField(blank=True, verbose_name='last error msg')),
                ('user', models.ForeignKey(blank=True, help_text='Set when the backing connector is user-scoped; null for workspace-scoped connectors.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_connections', related_query_name='integration_connection', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_connections', related_query_name='integration_connection', to='workspaces.workspace')),
                ('token', models.ForeignKey(help_text='The OAuthToken backing this binding. N:1 — one token can back multiple Connections (Gmail + Drive share Google token).', on_delete=django.db.models.deletion.CASCADE, related_name='connections', related_query_name='connection', to='integrations.oauthtoken')),
            ],
            options={
                'verbose_name': 'Integration Connection',
                'verbose_name_plural': 'Integration Connections',
                'db_table': 'integration_connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientcredentials',
            index=models.Index(fields=['slug', 'workspace'], name='client_cred_slug_b6bc0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientcredentials',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', True)), fields=('slug',), name='uq_clientcred_slug_global'),
        ),
        migrations.AddConstraint(
            model_name='clientcredentials',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', False)), fields=('slug', 'workspace'), name='uq_clientcred_slug_workspace'),
        ),
        migrations.AddIndex(
            model_name='oauthtoken',
            index=models.Index(fields=['provider', 'user'], name='oauth_token_provide_db0a52_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthtoken',
            index=models.Index(fields=['provider', 'workspace'], name='oauth_token_provide_886256_idx'),
        ),
        migrations.AddConstraint(
            model_name='oauthtoken',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('workspace__isnull', True)), models.Q(('user__isnull', True), ('workspace__isnull', False)), _connector='OR'), name='oauth_token_has_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='oauthtoken',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('provider', 'user'), name='uq_oauth_token_per_user_provider'),
        ),
        migrations.AddConstraint(
            model_name='oauthtoken',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', False)), fields=('provider', 'workspace'), name='uq_oauth_token_per_workspace_provider'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['workspace', 'provider_slug', 'enabled'], name='integration_workspa_cd3d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['token'], name='integration_token_i_266f26_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['last_synced_at'], name='integration_last_sy_650c38_idx'),
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(fields=('workspace', 'user', 'provider_slug'), name='uq_connection_ws_user_provider'),
        ),
    ]
