# Generated by Django 6.0.5 on 2026-05-22 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_clientcredentials_oauthtoken_connection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcredentials',
            name='authorize_url',
        ),
        migrations.RemoveField(
            model_name='clientcredentials',
            name='default_scopes',
        ),
        migrations.RemoveField(
            model_name='clientcredentials',
            name='token_url',
        ),
    ]
