// AUTO-GENERATED by server/scripts/sync_emojis.py.
// Source of truth: server/donna/chat/emojis.py — DO NOT edit this file by hand.

export interface EmojiEntry {
  code: string;
  unicode: string;
  group: string;
  keywords: string[];
}

export const CURATED_EMOJIS: EmojiEntry[] = [
  {
    "code": "smile",
    "unicode": "😄",
    "group": "people",
    "keywords": [
      "happy",
      "joy"
    ]
  },
  {
    "code": "laughing",
    "unicode": "😆",
    "group": "people",
    "keywords": [
      "lol",
      "haha"
    ]
  },
  {
    "code": "joy",
    "unicode": "😂",
    "group": "people",
    "keywords": [
      "cry",
      "laugh"
    ]
  },
  {
    "code": "rofl",
    "unicode": "🤣",
    "group": "people",
    "keywords": [
      "rolling",
      "laughing"
    ]
  },
  {
    "code": "wink",
    "unicode": "😉",
    "group": "people",
    "keywords": [
      "flirt"
    ]
  },
  {
    "code": "blush",
    "unicode": "😊",
    "group": "people",
    "keywords": [
      "smile",
      "happy"
    ]
  },
  {
    "code": "heart_eyes",
    "unicode": "😍",
    "group": "people",
    "keywords": [
      "love"
    ]
  },
  {
    "code": "smirk",
    "unicode": "😏",
    "group": "people",
    "keywords": []
  },
  {
    "code": "thinking",
    "unicode": "🤔",
    "group": "people",
    "keywords": [
      "hmm",
      "think"
    ]
  },
  {
    "code": "neutral_face",
    "unicode": "😐",
    "group": "people",
    "keywords": [
      "meh"
    ]
  },
  {
    "code": "expressionless",
    "unicode": "😑",
    "group": "people",
    "keywords": []
  },
  {
    "code": "unamused",
    "unicode": "😒",
    "group": "people",
    "keywords": [
      "meh"
    ]
  },
  {
    "code": "eyes",
    "unicode": "👀",
    "group": "people",
    "keywords": [
      "look",
      "watch"
    ]
  },
  {
    "code": "sob",
    "unicode": "😭",
    "group": "people",
    "keywords": [
      "cry",
      "sad"
    ]
  },
  {
    "code": "cry",
    "unicode": "😢",
    "group": "people",
    "keywords": [
      "sad"
    ]
  },
  {
    "code": "scream",
    "unicode": "😱",
    "group": "people",
    "keywords": [
      "shock"
    ]
  },
  {
    "code": "angry",
    "unicode": "😠",
    "group": "people",
    "keywords": [
      "mad"
    ]
  },
  {
    "code": "rage",
    "unicode": "😡",
    "group": "people",
    "keywords": [
      "furious"
    ]
  },
  {
    "code": "tired_face",
    "unicode": "😫",
    "group": "people",
    "keywords": [
      "exhausted"
    ]
  },
  {
    "code": "weary",
    "unicode": "😩",
    "group": "people",
    "keywords": [
      "tired"
    ]
  },
  {
    "code": "sweat_smile",
    "unicode": "😅",
    "group": "people",
    "keywords": [
      "phew"
    ]
  },
  {
    "code": "sweat",
    "unicode": "😓",
    "group": "people",
    "keywords": []
  },
  {
    "code": "disappointed",
    "unicode": "😞",
    "group": "people",
    "keywords": [
      "sad"
    ]
  },
  {
    "code": "confused",
    "unicode": "😕",
    "group": "people",
    "keywords": []
  },
  {
    "code": "worried",
    "unicode": "😟",
    "group": "people",
    "keywords": []
  },
  {
    "code": "kissing_heart",
    "unicode": "😘",
    "group": "people",
    "keywords": []
  },
  {
    "code": "yum",
    "unicode": "😋",
    "group": "people",
    "keywords": [
      "tasty"
    ]
  },
  {
    "code": "stuck_out_tongue",
    "unicode": "😛",
    "group": "people",
    "keywords": []
  },
  {
    "code": "sunglasses",
    "unicode": "😎",
    "group": "people",
    "keywords": [
      "cool"
    ]
  },
  {
    "code": "nerd_face",
    "unicode": "🤓",
    "group": "people",
    "keywords": [
      "geek"
    ]
  },
  {
    "code": "exploding_head",
    "unicode": "🤯",
    "group": "people",
    "keywords": [
      "mindblown"
    ]
  },
  {
    "code": "cowboy",
    "unicode": "🤠",
    "group": "people",
    "keywords": []
  },
  {
    "code": "partying_face",
    "unicode": "🥳",
    "group": "people",
    "keywords": [
      "party"
    ]
  },
  {
    "code": "smiling_imp",
    "unicode": "😈",
    "group": "people",
    "keywords": [
      "evil"
    ]
  },
  {
    "code": "skull",
    "unicode": "💀",
    "group": "people",
    "keywords": [
      "dead"
    ]
  },
  {
    "code": "ghost",
    "unicode": "👻",
    "group": "people",
    "keywords": []
  },
  {
    "code": "robot",
    "unicode": "🤖",
    "group": "people",
    "keywords": [
      "bot",
      "ai"
    ]
  },
  {
    "code": "wave",
    "unicode": "👋",
    "group": "people",
    "keywords": [
      "hi",
      "bye"
    ]
  },
  {
    "code": "raised_hands",
    "unicode": "🙌",
    "group": "people",
    "keywords": [
      "praise",
      "celebrate"
    ]
  },
  {
    "code": "clap",
    "unicode": "👏",
    "group": "people",
    "keywords": [
      "applause"
    ]
  },
  {
    "code": "pray",
    "unicode": "🙏",
    "group": "people",
    "keywords": [
      "thanks",
      "please"
    ]
  },
  {
    "code": "muscle",
    "unicode": "💪",
    "group": "people",
    "keywords": [
      "strong"
    ]
  },
  {
    "code": "ok_hand",
    "unicode": "👌",
    "group": "people",
    "keywords": [
      "ok",
      "perfect"
    ]
  },
  {
    "code": "v",
    "unicode": "✌️",
    "group": "people",
    "keywords": [
      "peace"
    ]
  },
  {
    "code": "crossed_fingers",
    "unicode": "🤞",
    "group": "people",
    "keywords": [
      "luck",
      "hope"
    ]
  },
  {
    "code": "thumbsup",
    "unicode": "👍",
    "group": "people",
    "keywords": [
      "yes",
      "agree",
      "good"
    ]
  },
  {
    "code": "thumbsdown",
    "unicode": "👎",
    "group": "people",
    "keywords": [
      "no",
      "disagree"
    ]
  },
  {
    "code": "point_right",
    "unicode": "👉",
    "group": "people",
    "keywords": []
  },
  {
    "code": "point_left",
    "unicode": "👈",
    "group": "people",
    "keywords": []
  },
  {
    "code": "point_up",
    "unicode": "👆",
    "group": "people",
    "keywords": [
      "fyi"
    ]
  },
  {
    "code": "raising_hand",
    "unicode": "🙋",
    "group": "people",
    "keywords": [
      "volunteer"
    ]
  },
  {
    "code": "facepalm",
    "unicode": "🤦",
    "group": "people",
    "keywords": []
  },
  {
    "code": "shrug",
    "unicode": "🤷",
    "group": "people",
    "keywords": [
      "idk"
    ]
  },
  {
    "code": "bow",
    "unicode": "🙇",
    "group": "people",
    "keywords": [
      "sorry"
    ]
  },
  {
    "code": "handshake",
    "unicode": "🤝",
    "group": "people",
    "keywords": [
      "deal",
      "agree"
    ]
  },
  {
    "code": "heart",
    "unicode": "❤️",
    "group": "symbols",
    "keywords": [
      "love"
    ]
  },
  {
    "code": "orange_heart",
    "unicode": "🧡",
    "group": "symbols",
    "keywords": []
  },
  {
    "code": "yellow_heart",
    "unicode": "💛",
    "group": "symbols",
    "keywords": []
  },
  {
    "code": "green_heart",
    "unicode": "💚",
    "group": "symbols",
    "keywords": []
  },
  {
    "code": "blue_heart",
    "unicode": "💙",
    "group": "symbols",
    "keywords": []
  },
  {
    "code": "purple_heart",
    "unicode": "💜",
    "group": "symbols",
    "keywords": []
  },
  {
    "code": "black_heart",
    "unicode": "🖤",
    "group": "symbols",
    "keywords": []
  },
  {
    "code": "white_heart",
    "unicode": "🤍",
    "group": "symbols",
    "keywords": []
  },
  {
    "code": "broken_heart",
    "unicode": "💔",
    "group": "symbols",
    "keywords": [
      "sad"
    ]
  },
  {
    "code": "two_hearts",
    "unicode": "💕",
    "group": "symbols",
    "keywords": []
  },
  {
    "code": "sparkling_heart",
    "unicode": "💖",
    "group": "symbols",
    "keywords": []
  },
  {
    "code": "100",
    "unicode": "💯",
    "group": "symbols",
    "keywords": [
      "perfect",
      "score"
    ]
  },
  {
    "code": "checkmark",
    "unicode": "✅",
    "group": "symbols",
    "keywords": [
      "done",
      "ok",
      "yes"
    ]
  },
  {
    "code": "x",
    "unicode": "❌",
    "group": "symbols",
    "keywords": [
      "no",
      "wrong"
    ]
  },
  {
    "code": "warning",
    "unicode": "⚠️",
    "group": "symbols",
    "keywords": [
      "alert",
      "caution"
    ]
  },
  {
    "code": "no_entry",
    "unicode": "⛔",
    "group": "symbols",
    "keywords": [
      "stop"
    ]
  },
  {
    "code": "question",
    "unicode": "❓",
    "group": "symbols",
    "keywords": []
  },
  {
    "code": "exclamation",
    "unicode": "❗",
    "group": "symbols",
    "keywords": []
  },
  {
    "code": "bangbang",
    "unicode": "‼️",
    "group": "symbols",
    "keywords": []
  },
  {
    "code": "interrobang",
    "unicode": "⁉️",
    "group": "symbols",
    "keywords": []
  },
  {
    "code": "white_check_mark",
    "unicode": "✔️",
    "group": "symbols",
    "keywords": [
      "done"
    ]
  },
  {
    "code": "sparkles",
    "unicode": "✨",
    "group": "symbols",
    "keywords": [
      "magic",
      "new"
    ]
  },
  {
    "code": "boom",
    "unicode": "💥",
    "group": "symbols",
    "keywords": [
      "explosion"
    ]
  },
  {
    "code": "fire",
    "unicode": "🔥",
    "group": "symbols",
    "keywords": [
      "hot",
      "lit",
      "great"
    ]
  },
  {
    "code": "star",
    "unicode": "⭐",
    "group": "symbols",
    "keywords": [
      "favorite"
    ]
  },
  {
    "code": "star2",
    "unicode": "🌟",
    "group": "symbols",
    "keywords": []
  },
  {
    "code": "zap",
    "unicode": "⚡",
    "group": "symbols",
    "keywords": [
      "lightning",
      "fast"
    ]
  },
  {
    "code": "snowflake",
    "unicode": "❄️",
    "group": "symbols",
    "keywords": [
      "cold"
    ]
  },
  {
    "code": "rocket",
    "unicode": "🚀",
    "group": "objects",
    "keywords": [
      "launch",
      "ship",
      "go"
    ]
  },
  {
    "code": "tada",
    "unicode": "🎉",
    "group": "objects",
    "keywords": [
      "celebrate",
      "party"
    ]
  },
  {
    "code": "confetti_ball",
    "unicode": "🎊",
    "group": "objects",
    "keywords": []
  },
  {
    "code": "balloon",
    "unicode": "🎈",
    "group": "objects",
    "keywords": [
      "party"
    ]
  },
  {
    "code": "gift",
    "unicode": "🎁",
    "group": "objects",
    "keywords": [
      "present"
    ]
  },
  {
    "code": "trophy",
    "unicode": "🏆",
    "group": "objects",
    "keywords": [
      "win"
    ]
  },
  {
    "code": "medal",
    "unicode": "🏅",
    "group": "objects",
    "keywords": []
  },
  {
    "code": "first_place",
    "unicode": "🥇",
    "group": "objects",
    "keywords": [
      "winner"
    ]
  },
  {
    "code": "second_place",
    "unicode": "🥈",
    "group": "objects",
    "keywords": []
  },
  {
    "code": "third_place",
    "unicode": "🥉",
    "group": "objects",
    "keywords": []
  },
  {
    "code": "bulb",
    "unicode": "💡",
    "group": "objects",
    "keywords": [
      "idea"
    ]
  },
  {
    "code": "memo",
    "unicode": "📝",
    "group": "objects",
    "keywords": [
      "note",
      "write"
    ]
  },
  {
    "code": "books",
    "unicode": "📚",
    "group": "objects",
    "keywords": [
      "read",
      "study"
    ]
  },
  {
    "code": "computer",
    "unicode": "💻",
    "group": "objects",
    "keywords": [
      "laptop"
    ]
  },
  {
    "code": "iphone",
    "unicode": "📱",
    "group": "objects",
    "keywords": [
      "phone"
    ]
  },
  {
    "code": "telephone",
    "unicode": "☎️",
    "group": "objects",
    "keywords": [
      "call"
    ]
  },
  {
    "code": "email",
    "unicode": "📧",
    "group": "objects",
    "keywords": [
      "mail"
    ]
  },
  {
    "code": "calendar",
    "unicode": "📅",
    "group": "objects",
    "keywords": [
      "date",
      "schedule"
    ]
  },
  {
    "code": "clock",
    "unicode": "🕐",
    "group": "objects",
    "keywords": [
      "time"
    ]
  },
  {
    "code": "hourglass",
    "unicode": "⌛",
    "group": "objects",
    "keywords": [
      "wait"
    ]
  },
  {
    "code": "lock",
    "unicode": "🔒",
    "group": "objects",
    "keywords": [
      "secure"
    ]
  },
  {
    "code": "unlock",
    "unicode": "🔓",
    "group": "objects",
    "keywords": []
  },
  {
    "code": "key",
    "unicode": "🔑",
    "group": "objects",
    "keywords": []
  },
  {
    "code": "hammer",
    "unicode": "🔨",
    "group": "objects",
    "keywords": [
      "build",
      "fix"
    ]
  },
  {
    "code": "wrench",
    "unicode": "🔧",
    "group": "objects",
    "keywords": [
      "fix"
    ]
  },
  {
    "code": "gear",
    "unicode": "⚙️",
    "group": "objects",
    "keywords": [
      "settings",
      "config"
    ]
  },
  {
    "code": "package",
    "unicode": "📦",
    "group": "objects",
    "keywords": [
      "ship",
      "box"
    ]
  },
  {
    "code": "scroll",
    "unicode": "📜",
    "group": "objects",
    "keywords": [
      "docs"
    ]
  },
  {
    "code": "clipboard",
    "unicode": "📋",
    "group": "objects",
    "keywords": []
  },
  {
    "code": "paperclip",
    "unicode": "📎",
    "group": "objects",
    "keywords": [
      "attachment"
    ]
  },
  {
    "code": "magnifying_glass",
    "unicode": "🔍",
    "group": "objects",
    "keywords": [
      "search"
    ]
  },
  {
    "code": "link",
    "unicode": "🔗",
    "group": "objects",
    "keywords": [
      "url"
    ]
  },
  {
    "code": "bookmark",
    "unicode": "🔖",
    "group": "objects",
    "keywords": []
  },
  {
    "code": "wave_emoji",
    "unicode": "🌊",
    "group": "nature",
    "keywords": [
      "wave",
      "water"
    ]
  },
  {
    "code": "sun",
    "unicode": "☀️",
    "group": "nature",
    "keywords": [
      "sunny"
    ]
  },
  {
    "code": "cloud",
    "unicode": "☁️",
    "group": "nature",
    "keywords": []
  },
  {
    "code": "rainbow",
    "unicode": "🌈",
    "group": "nature",
    "keywords": []
  },
  {
    "code": "snowman",
    "unicode": "⛄",
    "group": "nature",
    "keywords": []
  },
  {
    "code": "leaves",
    "unicode": "🍃",
    "group": "nature",
    "keywords": [
      "green"
    ]
  },
  {
    "code": "deciduous_tree",
    "unicode": "🌳",
    "group": "nature",
    "keywords": []
  },
  {
    "code": "rose",
    "unicode": "🌹",
    "group": "nature",
    "keywords": [
      "flower"
    ]
  },
  {
    "code": "tulip",
    "unicode": "🌷",
    "group": "nature",
    "keywords": []
  },
  {
    "code": "dog",
    "unicode": "🐶",
    "group": "nature",
    "keywords": []
  },
  {
    "code": "cat",
    "unicode": "🐱",
    "group": "nature",
    "keywords": []
  },
  {
    "code": "unicorn",
    "unicode": "🦄",
    "group": "nature",
    "keywords": []
  },
  {
    "code": "owl",
    "unicode": "🦉",
    "group": "nature",
    "keywords": []
  },
  {
    "code": "coffee",
    "unicode": "☕",
    "group": "food",
    "keywords": [
      "caffeine"
    ]
  },
  {
    "code": "tea",
    "unicode": "🍵",
    "group": "food",
    "keywords": []
  },
  {
    "code": "beer",
    "unicode": "🍺",
    "group": "food",
    "keywords": []
  },
  {
    "code": "wine",
    "unicode": "🍷",
    "group": "food",
    "keywords": []
  },
  {
    "code": "champagne",
    "unicode": "🍾",
    "group": "food",
    "keywords": [
      "celebrate"
    ]
  },
  {
    "code": "cake",
    "unicode": "🎂",
    "group": "food",
    "keywords": [
      "birthday"
    ]
  },
  {
    "code": "pizza",
    "unicode": "🍕",
    "group": "food",
    "keywords": []
  },
  {
    "code": "donut",
    "unicode": "🍩",
    "group": "food",
    "keywords": []
  },
  {
    "code": "popcorn",
    "unicode": "🍿",
    "group": "food",
    "keywords": []
  },
  {
    "code": "taco",
    "unicode": "🌮",
    "group": "food",
    "keywords": []
  },
  {
    "code": "soccer",
    "unicode": "⚽",
    "group": "activity",
    "keywords": []
  },
  {
    "code": "basketball",
    "unicode": "🏀",
    "group": "activity",
    "keywords": []
  },
  {
    "code": "tennis",
    "unicode": "🎾",
    "group": "activity",
    "keywords": []
  },
  {
    "code": "8ball",
    "unicode": "🎱",
    "group": "activity",
    "keywords": []
  },
  {
    "code": "video_game",
    "unicode": "🎮",
    "group": "activity",
    "keywords": []
  },
  {
    "code": "dart",
    "unicode": "🎯",
    "group": "activity",
    "keywords": [
      "target",
      "goal"
    ]
  },
  {
    "code": "guitar",
    "unicode": "🎸",
    "group": "activity",
    "keywords": []
  },
  {
    "code": "musical_note",
    "unicode": "🎵",
    "group": "activity",
    "keywords": []
  },
  {
    "code": "art",
    "unicode": "🎨",
    "group": "activity",
    "keywords": []
  },
  {
    "code": "airplane",
    "unicode": "✈️",
    "group": "travel",
    "keywords": []
  },
  {
    "code": "car",
    "unicode": "🚗",
    "group": "travel",
    "keywords": []
  },
  {
    "code": "bike",
    "unicode": "🚲",
    "group": "travel",
    "keywords": []
  },
  {
    "code": "rocket_travel",
    "unicode": "🛸",
    "group": "travel",
    "keywords": [
      "ufo"
    ]
  },
  {
    "code": "earth",
    "unicode": "🌍",
    "group": "travel",
    "keywords": [
      "world"
    ]
  },
  {
    "code": "globe",
    "unicode": "🌐",
    "group": "travel",
    "keywords": [
      "www"
    ]
  },
  {
    "code": "house",
    "unicode": "🏠",
    "group": "travel",
    "keywords": [
      "home"
    ]
  },
  {
    "code": "office",
    "unicode": "🏢",
    "group": "travel",
    "keywords": [
      "work"
    ]
  },
  {
    "code": "tent",
    "unicode": "⛺",
    "group": "travel",
    "keywords": [
      "camping"
    ]
  },
  {
    "code": "moneybag",
    "unicode": "💰",
    "group": "objects",
    "keywords": [
      "money",
      "cash"
    ]
  },
  {
    "code": "dollar",
    "unicode": "💵",
    "group": "objects",
    "keywords": [
      "money"
    ]
  },
  {
    "code": "credit_card",
    "unicode": "💳",
    "group": "objects",
    "keywords": [
      "payment"
    ]
  },
  {
    "code": "chart_up",
    "unicode": "📈",
    "group": "objects",
    "keywords": [
      "growth"
    ]
  },
  {
    "code": "chart_down",
    "unicode": "📉",
    "group": "objects",
    "keywords": [
      "decline"
    ]
  },
  {
    "code": "bar_chart",
    "unicode": "📊",
    "group": "objects",
    "keywords": []
  },
  {
    "code": "construction",
    "unicode": "🚧",
    "group": "symbols",
    "keywords": [
      "wip"
    ]
  },
  {
    "code": "speech_balloon",
    "unicode": "💬",
    "group": "symbols",
    "keywords": [
      "comment"
    ]
  },
  {
    "code": "thought_balloon",
    "unicode": "💭",
    "group": "symbols",
    "keywords": [
      "idea"
    ]
  },
  {
    "code": "zzz",
    "unicode": "💤",
    "group": "symbols",
    "keywords": [
      "sleep"
    ]
  },
  {
    "code": "bell",
    "unicode": "🔔",
    "group": "objects",
    "keywords": [
      "notify"
    ]
  },
  {
    "code": "no_bell",
    "unicode": "🔕",
    "group": "objects",
    "keywords": [
      "mute"
    ]
  },
  {
    "code": "loudspeaker",
    "unicode": "📢",
    "group": "objects",
    "keywords": [
      "announce"
    ]
  },
  {
    "code": "mega",
    "unicode": "📣",
    "group": "objects",
    "keywords": [
      "announce"
    ]
  },
  {
    "code": "flag_us",
    "unicode": "🇺🇸",
    "group": "flags",
    "keywords": []
  },
  {
    "code": "flag_eu",
    "unicode": "🇪🇺",
    "group": "flags",
    "keywords": []
  },
  {
    "code": "flag_ro",
    "unicode": "🇷🇴",
    "group": "flags",
    "keywords": []
  },
  {
    "code": "checkered_flag",
    "unicode": "🏁",
    "group": "symbols",
    "keywords": [
      "finish",
      "done"
    ]
  },
  {
    "code": "white_flag",
    "unicode": "🏳️",
    "group": "symbols",
    "keywords": [
      "surrender"
    ]
  },
  {
    "code": "rainbow_flag",
    "unicode": "🏳️‍🌈",
    "group": "flags",
    "keywords": [
      "pride"
    ]
  }
];

export const EMOJIS_BY_CODE: Record<string, EmojiEntry> = Object.fromEntries(
  CURATED_EMOJIS.map((e) => [e.code, e]),
);
