# Generated by Django 6.0.5 on 2026-06-02 11:53

import django.db.models.deletion
import donna.workspaces.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceInvitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=16)),
                ('token', models.CharField(default=donna.workspaces.models._default_invitation_token, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(default=donna.workspaces.models._default_invitation_expiry)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_accepted', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspace_invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='workspace_i_workspa_814b7e_idx'), models.Index(fields=['email', 'status'], name='workspace_i_email_03d7f7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('role', 'owner'), _negated=True), name='invitation_role_not_owner')],
            },
        ),
    ]
