# Generated by Django 6.0.5 on 2026-06-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='primary_domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
