# Generated by Django 6.0.5 on 2026-06-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verified_user_email_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='handle',
            field=models.CharField(blank=True, help_text="Lowercase mention handle, e.g. 'alice' resolves @alice.", max_length=40, null=True, unique=True),
        ),
    ]
