# Generated by Django 6.0.5 on 2026-07-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='users/pictures/', verbose_name='profile picture'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, default='', max_length=140, verbose_name='status'),
        ),
    ]
