# Generated by Django 6.0.5 on 2026-07-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_picture_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_away',
            field=models.BooleanField(default=False, verbose_name='away'),
        ),
    ]
