# Generated by Django 6.0.5 on 2026-05-19 21:22

import donna.core.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(help_text='Stable identifier; matches connector class `oauth_provider_slug`.', max_length=64, unique=True, verbose_name='slug')),
                ('display_name', models.CharField(max_length=120, verbose_name='display name')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='is enabled')),
                ('client_id', models.CharField(blank=True, max_length=255, verbose_name='client id')),
                ('client_secret', donna.core.db.fields.EncryptedTextField(blank=True, verbose_name='client secret')),
                ('redirect_uri', models.URLField(blank=True, verbose_name='redirect uri')),
                ('authorize_url', models.URLField(blank=True, verbose_name='authorize url')),
                ('token_url', models.URLField(blank=True, verbose_name='token url')),
                ('default_scopes', models.JSONField(blank=True, default=list, verbose_name='default scopes')),
                ('webhook_secret', donna.core.db.fields.EncryptedTextField(blank=True, verbose_name='webhook secret')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'OAuth Provider',
                'verbose_name_plural': 'OAuth Providers',
                'db_table': 'oauth_providers',
            },
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', donna.core.db.fields.EncryptedTextField(blank=True, null=True, verbose_name='access token')),
                ('refresh_token', donna.core.db.fields.EncryptedTextField(blank=True, null=True, verbose_name='refresh token')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the current access_token expires (UTC).', null=True, verbose_name='access token expiry')),
                ('scope', models.TextField(blank=True, null=True, verbose_name='scope')),
            ],
            options={
                'verbose_name': 'OAuth token',
                'verbose_name_plural': 'OAuth tokens',
                'db_table': 'oauth_tokens',
            },
        ),
    ]
