# Generated by Django 6.0.5 on 2026-05-19 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthprovider',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oauthprovider',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oauthtoken',
            name='granter',
            field=models.ForeignKey(blank=True, help_text='User who authorized a workspace-scoped token.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_oauth_tokens', related_query_name='granted_oauth_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oauthtoken',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', related_query_name='token', to='authentication.oauthprovider'),
        ),
        migrations.AddField(
            model_name='oauthtoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_tokens', related_query_name='oauth_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oauthtoken',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_tokens', related_query_name='oauth_token', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='oauthprovider',
            index=models.Index(fields=['slug'], name='oauth_provi_slug_f7674a_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthtoken',
            index=models.Index(fields=['provider', 'user'], name='oauth_token_provide_db0a52_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthtoken',
            index=models.Index(fields=['provider', 'workspace'], name='oauth_token_provide_886256_idx'),
        ),
        migrations.AddConstraint(
            model_name='oauthtoken',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('workspace__isnull', True)), models.Q(('user__isnull', True), ('workspace__isnull', False)), _connector='OR'), name='oauth_token_has_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='oauthtoken',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('provider', 'user'), name='uq_oauth_token_per_user_provider'),
        ),
        migrations.AddConstraint(
            model_name='oauthtoken',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', False)), fields=('provider', 'workspace'), name='uq_oauth_token_per_workspace_provider'),
        ),
    ]
