# Generated by Django 6.0.5 on 2026-05-19 21:46

import donna.core.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthprovider',
            name='authorize_url',
            field=models.URLField(blank=True, default='', verbose_name='authorize url'),
        ),
        migrations.AlterField(
            model_name='oauthprovider',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='client id'),
        ),
        migrations.AlterField(
            model_name='oauthprovider',
            name='client_secret',
            field=donna.core.db.fields.EncryptedTextField(blank=True, null=True, verbose_name='client secret'),
        ),
        migrations.AlterField(
            model_name='oauthprovider',
            name='redirect_uri',
            field=models.URLField(blank=True, default='', verbose_name='redirect uri'),
        ),
        migrations.AlterField(
            model_name='oauthprovider',
            name='token_url',
            field=models.URLField(blank=True, default='', verbose_name='token url'),
        ),
        migrations.AlterField(
            model_name='oauthprovider',
            name='webhook_secret',
            field=donna.core.db.fields.EncryptedTextField(blank=True, null=True, verbose_name='webhook secret'),
        ),
    ]
