# Generated by Django 6.0.5 on 2026-05-21 21:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_oauthprovider_authorize_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email verification token',
                'verbose_name_plural': 'Email verification tokens',
                'db_table': 'email_verification_tokens',
            },
        ),
        migrations.CreateModel(
            name='ResetPasswordToken',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='token generation time')),
                ('expiry_at', models.DateTimeField(blank=True, null=True, verbose_name='token expiration time')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reset password token',
                'verbose_name_plural': 'Reset password tokens',
                'db_table': 'reset_password_tokens',
            },
        ),
        migrations.RemoveIndex(
            model_name='oauthprovider',
            name='oauth_provi_slug_f7674a_idx',
        ),
        migrations.RemoveIndex(
            model_name='oauthtoken',
            name='oauth_token_provide_db0a52_idx',
        ),
        migrations.RemoveIndex(
            model_name='oauthtoken',
            name='oauth_token_provide_886256_idx',
        ),
        migrations.RemoveConstraint(
            model_name='oauthtoken',
            name='oauth_token_has_exactly_one_owner',
        ),
        migrations.RemoveConstraint(
            model_name='oauthtoken',
            name='uq_oauth_token_per_user_provider',
        ),
        migrations.RemoveConstraint(
            model_name='oauthtoken',
            name='uq_oauth_token_per_workspace_provider',
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', related_query_name='email_verification_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resetpasswordtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_password_tokens', related_query_name='reset_password_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='oauthtoken',
            name='granter',
        ),
        migrations.RemoveField(
            model_name='oauthtoken',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='oauthtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='oauthtoken',
            name='workspace',
        ),
        migrations.DeleteModel(
            name='OAuthProvider',
        ),
        migrations.DeleteModel(
            name='OAuthToken',
        ),
    ]
