# Generated by Django 6.0.5 on 2026-05-21 21:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('status', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=50, verbose_name='status')),
                ('type', models.CharField(default='info', max_length=50, verbose_name='type')),
                ('seen', models.BooleanField(default=False, verbose_name='is read')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='context')),
                ('scope', models.CharField(choices=[('user', 'User'), ('workspace', 'Workspace'), ('user_in_workspace', 'User in workspace')], default='user', help_text='Which SSE channel this notification was published on (see plans/10-realtime-layer.md).', max_length=32, verbose_name='scope')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', related_query_name='notification', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', related_query_name='notification', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['user', 'seen'], name='notificatio_user_id_3b0f12_idx'), models.Index(fields=['workspace', '-created_at'], name='notificatio_workspa_5e4b93_idx'), models.Index(fields=['user', 'workspace', '-created_at'], name='notificatio_user_id_e8fe6e_idx')],
            },
        ),
    ]
