// Vault data — rich archival items with type-specific fields
window.VAULT_DATA = (function () {
  const items = [
    {
      id: "v1",
      type: "decision",
      title: "Standardize on RECIST v3 — not v2 + custom extension",
      who: "marko",
      when: "Apr 8, 2026 · 2:14 PM",
      where: "#recist-protocol",
      ago: "8 days ago",
      summary: "Adopting v3 wholesale rather than carrying a forked v2.1 forward.",
      considered: [
        { option: "v3 (chosen)", verdict: "Adopted. Aligns with peer institutions, supports volumetric.", chosen: true },
        { option: "v2 + Cube extension", verdict: "Slows interop. Maintenance burden over 18mo." },
        { option: "Defer 3 months", verdict: "Loses Q2 window with clinical partners." }
      ],
      rationale: "Three of four clinical partners moved to v3 in Q1. Carrying a fork increases divergence and review time. Volumetric support unblocks the imaging-AI workstream Mira and Kai are scoping.",
      decided_by: ["marko", "rebeca"],
      consulted: ["alice", "mira", "donna"],
      affected: ["#recist-protocol", "#recist-data", "#recist-clinicians"],
      followups: 3,
      runs: 1,
      tags: ["protocol", "strategic", "Q2"],
      thread: 24,
    },
    {
      id: "v2",
      type: "run",
      title: "Q1 clinical-ops review · 14 metrics, 3 anomalies",
      who: "donna",
      when: "Apr 2, 2026 · 9:18 AM",
      where: "Personal · marius",
      ago: "2 weeks ago",
      summary: "Donna pulled Q1 figures and surfaced 3 anomalies worth investigating.",
      duration: "1m 42s",
      tokens: "12.4k",
      tools: [
        { name: "Warehouse", calls: 8 },
        { name: "Drive", calls: 3 },
        { name: "Sheets", calls: 2 },
      ],
      output_preview: "Scans processed: 4,218 (+22%). Median turnaround: 41h (target <48). Label drift on coronal slices ↑ 7%. Three anomalies: drift cluster on Tue/Thu shifts, dropped Q1W4 from one site, unexplained reviewer-disagreement spike Mar 28.",
      learned: [
        "Q1 baseline: 4,218 scans processed",
        "Coronal slice label drift trending up",
        "Tue/Thu reviewer rotation may correlate with drift"
      ],
      tags: ["agent run", "quarterly", "metrics"],
    },
    {
      id: "v3",
      type: "doc",
      title: "RECIST_v3_protocol.pdf",
      who: "rebeca",
      when: "Mar 28, 2026",
      where: "Drive · /recist",
      ago: "3 weeks ago",
      summary: "Official v3 protocol PDF, 42 pages, lesion measurement & follow-up cadence.",
      pages: 42,
      size: "2.1 MB",
      readers: ["marko", "rebeca", "alice", "marius"],
      cited_in: 14,
      ai_indexed: true,
      excerpt: "Target lesions selected at baseline shall not exceed five total, no more than two per organ. Sum of diameters serves as the baseline reference for response classification.",
      tags: ["protocol", "reference"],
    },
    {
      id: "v4",
      type: "link",
      title: "ClinicalTrials.gov · NCT06782233 — comparable imaging trial",
      who: "mira",
      when: "Mar 26, 2026",
      where: "#recist-protocol",
      ago: "3 weeks ago",
      summary: "Phase II, n=240, baseline + 4 follow-ups at 6-week cadence. Mira flagged as closest match.",
      domain: "clinicaltrials.gov",
      shared_in: ["#recist-protocol", "#recist-data"],
      notes: "Closest match to our cadence. Note: they use Q-CT not MR.",
      tags: ["research", "reference"],
    },
    {
      id: "v5",
      type: "decision",
      title: "Defer launch press to May 6 (was Apr 22)",
      who: "marius",
      when: "Mar 22, 2026",
      where: "#launch-press",
      ago: "4 weeks ago",
      summary: "Pushing 2 weeks to align with Series B close + clinical milestone.",
      considered: [
        { option: "May 6 (chosen)", verdict: "Aligns with Series B + first clinical signoff.", chosen: true },
        { option: "Apr 22 (original)", verdict: "Risk: missing the clinical proof point." },
        { option: "Late May", verdict: "Conflicts with HIMSS." }
      ],
      rationale: "Press without the clinical proof point is weaker. May 6 lets us lead with the first signed-off site.",
      decided_by: ["marius"],
      consulted: ["atlas", "nova", "donna"],
      affected: ["#launch-press", "#launch-plan"],
      followups: 5,
      tags: ["launch", "strategic"],
    },
    {
      id: "v6",
      type: "run",
      title: "Competitor scan: imaging AI · 12 companies, 4 standouts",
      who: "atlas",
      when: "Feb 28, 2026",
      where: "#launch-press",
      ago: "6 weeks ago",
      summary: "Atlas mapped the imaging AI landscape, positioned Cube on clinical validation axis.",
      duration: "4m 12s",
      tokens: "38.1k",
      tools: [
        { name: "Web", calls: 47 },
        { name: "Crunchbase", calls: 12 },
        { name: "PubMed", calls: 5 },
      ],
      output_preview: "12 active companies in oncology imaging. 4 with >$50M funding: AidocVision, Volpara, Paige, Tempus. None have site-validated clinical workflows for RECIST volumetric. Cube's edge is clinical validation depth — not speed or scale.",
      tags: ["agent run", "research", "competitive"],
    },
    {
      id: "v7",
      type: "channel",
      title: "#all-cube (archived)",
      who: "marius",
      when: "Feb 14, 2026",
      where: "Workspace",
      ago: "9 weeks ago",
      summary: "Replaced by #room-1. Kept for searchability. 1,847 messages, Aug 2024 – Feb 2026.",
      messages: 1847,
      members: 14,
      tags: ["channel"],
    },
    {
      id: "v8",
      type: "doc",
      title: "Brand voice principles",
      who: "nova",
      when: "Feb 7, 2026",
      where: "Drive · /brand",
      ago: "10 weeks ago",
      summary: "Cube voice: clinical, direct, never breathless. 6 principles + examples.",
      pages: 4,
      size: "180 KB",
      readers: ["marius", "atlas", "nova"],
      cited_in: 6,
      excerpt: "Write like a senior clinician, not a marketer. Lead with the patient outcome, not the model. Never write 'AI-powered.'",
      tags: ["brand", "reference"],
    },
  ];

  const resurfaced = [
    {
      id: "r1",
      itemId: "v1",
      reason: "You're in #recist-protocol discussing lesion taxonomy — this decision set the v3 baseline.",
    },
    {
      id: "r2",
      itemId: "v6",
      reason: "Atlas's competitor scan referenced 'clinical validation depth' — relevant to Mira's current literature scan.",
    },
    {
      id: "r3",
      itemId: "v2",
      reason: "You asked Donna for Q1 numbers 12 minutes ago. This run already pulled them.",
    },
  ];

  return { items, resurfaced };
})();
