#!/usr/bin/env python3
"""Regenerate web/src/lib/emojis.ts from donna/chat/emojis.py.

Single source of truth = the Python dict. Run after editing the curated set:

    python server/scripts/sync_emojis.py

Idempotent; safe to run on every commit. Wire into CI to fail builds when
the two are out of sync.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
PY_FILE = REPO_ROOT / "server" / "donna" / "chat" / "emojis.py"
TS_FILE = REPO_ROOT / "web" / "src" / "lib" / "emojis.ts"


def main() -> int:
    # Exec the source file directly so we don't trigger ``donna/__init__.py``
    # (which pulls in celery + django). Keeps this script runnable from any
    # Python ≥3.10 without installing the project's dependencies.
    namespace: dict = {"__name__": "_emojis_loader"}
    exec(compile(PY_FILE.read_text(encoding="utf-8"), str(PY_FILE), "exec"), namespace)
    CURATED_EMOJIS = namespace["CURATED_EMOJIS"]

    entries = []
    for code, e in CURATED_EMOJIS.items():
        entries.append({
            "code": code,
            "unicode": e["unicode"],
            "group": e["group"],
            "keywords": e["keywords"],
        })

    ts_body = (
        "// AUTO-GENERATED by server/scripts/sync_emojis.py.\n"
        "// Source of truth: server/donna/chat/emojis.py — DO NOT edit this file by hand.\n\n"
        "export interface EmojiEntry {\n"
        "  code: string;\n"
        "  unicode: string;\n"
        "  group: string;\n"
        "  keywords: string[];\n"
        "}\n\n"
        "export const CURATED_EMOJIS: EmojiEntry[] = "
        + json.dumps(entries, indent=2, ensure_ascii=False)
        + ";\n\n"
        "export const EMOJIS_BY_CODE: Record<string, EmojiEntry> = Object.fromEntries(\n"
        "  CURATED_EMOJIS.map((e) => [e.code, e]),\n"
        ");\n"
    )

    TS_FILE.parent.mkdir(parents=True, exist_ok=True)
    TS_FILE.write_text(ts_body, encoding="utf-8")
    print(f"Wrote {len(entries)} emojis → {TS_FILE.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
