# Generated by Django 6.0.5 on 2026-05-21 21:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelReadState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='chat.channel')),
                ('last_read_message', models.ForeignKey(blank=True, help_text='Last message the user has read in this channel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_read_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel_read_states',
                'indexes': [models.Index(fields=['user', 'channel'], name='channel_rea_user_id_1ea8c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'channel'), name='uq_channel_read_state_user_channel')],
            },
        ),
    ]
