# Generated by Django 6.0.5 on 2026-06-20 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_channelreadstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='finalized_entity_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('drafting', 'Drafting'), ('finalized', 'Finalized'), ('abandoned', 'Abandoned')], default='drafting', max_length=12),
        ),
        migrations.AddField(
            model_name='document',
            name='target_doc_type',
            field=models.CharField(blank=True, default='', help_text='DocType vocab from cortex.schemas (passed to linter on finalize).', max_length=32),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'drafting')), fields=('channel',), name='uq_one_active_draft_per_channel'),
        ),
    ]
