# Generated by Django 6.0.5 on 2026-06-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_channelreadstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Per-channel behavior flags; see DEFAULT_SETTINGS for documented keys.'),
        ),
    ]
