# Generated by Django 6.0.5 on 2026-06-24 22:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_document_finalized_entity_id_document_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'channel_pins',
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'message_reactions',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='mention_flags',
            field=models.JSONField(blank=True, default=dict, help_text='Special mentions: {"donna": bool, "channel": bool, "everyone": bool}.'),
        ),
        migrations.AddField(
            model_name='message',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Thread parent. Top-level messages have parent=NULL.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='chat.message'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['parent', 'created_at'], name='messages_parent__83273b_idx'),
        ),
        migrations.AddField(
            model_name='channelpin',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='chat.channel'),
        ),
        migrations.AddField(
            model_name='channelpin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_pins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='author_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.message'),
        ),
        migrations.AddIndex(
            model_name='channelpin',
            index=models.Index(fields=['user'], name='channel_pin_user_id_c6b7f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='channelpin',
            constraint=models.UniqueConstraint(fields=('user', 'channel'), name='uq_channel_pin_user_channel'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message', 'emoji'], name='message_rea_message_7f9ef3_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagereaction',
            constraint=models.UniqueConstraint(fields=('message', 'emoji', 'author_user'), name='uq_reaction_user_message_emoji'),
        ),
    ]
